source/accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    path('log-in/', LogInView.as_view(), name='log_in'),
    path('log-out/', LogOutView.as_view(), name='log_out'),

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

source/app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView
from origo_scrape import views

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('', IndexPageView.as_view(), name='index'),
    path('', views.index, name="index"),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),

    
    path('start_scrape/', views.start_scrape, name="start_scrape"),
    path('get_scraping_status/', views.get_scraping_status, name="get_scraping_status"),
    path('get_xls_list/', views.get_xls_list, name="get_xls_list"),
    path('download', views.download, name="download"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/content/templates/layouts/default/page.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="utf-8" />
    <meta name="theme-color" content="#000000" />
    <title>Scrape</title>
    
    <link rel="icon" href="{% static 'favicon.ico' %}">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap" rel="stylesheet">
    
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <style>
        div.row {
            margin: 40px 0px;
            align-items: center;
        }

        div.row div.row, div.form-check{
            margin: 10px 0px;
        }

        .card-title {
            font-size: 25px;
            justify-content: center;
            display: flex;
            color: blue;
        }

        div.div-btn {
            margin-top: 20px !important;
        }

        div.container {
            width: 800px;
            margin-top: 40px;
            margin-bottom: 30px;
            /* margin: auto; */
            background-color:#FFFCF2;
            padding:30px;
            border-radius: 30px;
        }

        body {
            background-color: #E2E0FF;
            background-image: url("full-screen-image.jpg");
            background-size: cover;
            font-family: "Bree Serif";
        }

        .card {
            background-color: #f9fff9;
        }

        .card-body {
            padding-bottom: 10px;
        }

        .div-site {
            align-items: center;
        }

        .div-site div {
            text-align: right;
            font-size: 25px;
        }

        .btn-success {
            background-color: #A3E81A;
            border-color: #A3E81A;
        }

        .div-scrape-status {
            margin-bottom: 8px !important;
        }
        
        .text-muted {
            display: none;
        }

        .alert {
            position: absolute;
            top: 70px;
        }
    </style>

</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="/">{% trans 'Home' %}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault" style="display: block !important;">
        <ul class="navbar-nav mr-auto" style="float: right;">
            {% if request.user.is_authenticated %}
                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_password' %}">{% trans 'Change password' %}</a>
                </li> -->
                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_profile' %}">{% trans 'Change profile' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change_email' %}">{% trans 'Change email' %}</a>
                </li> -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:sign_up' %}">{% trans 'Create an account' %}</a>
                </li>
            {% endif %}
        </ul>

        <!-- <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'change_language' %}">{% trans 'Change language' %}</a>
            </li>
        </ul> -->
    </div>

</nav>

<div class="container-fluid mt-3m h-100" style="align-items: center; display: flex; justify-content: center; background-color: cadetblue;">
    
        {% bootstrap_messages %}
    
        {% block content %}
            No content.
        {% endblock %}
    
</div>

<script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>

</body>
</html>